name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target: [ aarch64-unknown-linux-gnu ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cross
      run: cargo install cross
    - name: build
      run: cross build --release --target ${{ matrix.target }} --verbose
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: aggro-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/aggro
